In [ ]:
from keras.models import load_model


In [ ]:
model = load_model("final.h5")

In [ ]:
x = input()

WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.


In [ ]:
s=[x]

In [ ]:
a =s

In [ ]:
a[0]

'WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.'

In [ ]:
import re
import string
from sklearn.feature_extraction.stop_words import ENGLISH_STOP_WORDS
def remove_hyperlink(word):
    return  re.sub(r"http\S+", "", word)

def to_lower(word):
    result = word.lower()
    return result

def remove_number(word):
    result = re.sub(r'\d+', '', word)
    return result

def remove_punctuation(word):
    result = word.translate(str.maketrans(dict.fromkeys(string.punctuation)))
    return result

def remove_whitespace(word):
    result = word.strip()
    return result

def replace_newline(word):
    return word.replace('\n','')



def clean_up_pipeline(sentence):
    cleaning_utils = [remove_hyperlink,
                      replace_newline,
                      to_lower,
                      remove_number,
                      remove_punctuation,remove_whitespace]
    for o in cleaning_utils:
        sentence = o(sentence)
    return sentence

In [ ]:
x_train = [clean_up_pipeline(o) for o in a]

In [ ]:
x_train =s

In [ ]:
## some config values 
embed_size = 100 # how big is each word vector
max_feature = 50000 # how many unique words to use (i.e num rows in embedding vector)
max_len = 2000 # max number of words in a question to use

In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=max_feature)

tokenizer.fit_on_texts(x_train)

x_train_features = np.array(tokenizer.texts_to_sequences(x_train))

In [ ]:
x_train_features

array([[ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1, 13, 14, 15, 16,  1,
         2, 17,  2, 18, 19, 20, 21, 22]])

In [ ]:
from keras.preprocessing.sequence import pad_sequences
x_train_features = pad_sequences(x_train_features,maxlen=max_len)
x_train_features[0]

array([ 0,  0,  0, ..., 20, 21, 22], dtype=int32)

In [ ]:
model.predict(x_train_features)


array([[0.24117792]], dtype=float32)

In [ ]:
y_predict  = [1 if o>0.5 else 0 for o in model.predict(x_train_features)]
y_predict

[0]